### ISSUE TITLE
SIMPLIFY - dry css

### ISSUE THREAD

**Issue by franfranfranfran** [4st3r1x/prj-rev-bwfs-dasmoto#1]
https://github.com/4st3r1x/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/css/index.css#L2
https://github.com/4st3r1x/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/css/index.css#L31
etc...

try to keep in mind dry principles when setting your css. are there any elements on the page that should not receive the helvetica font-family? can you set this styling just once for the entire page?

are there any other chunks of styling that we can avoid repeating?

**Comment by 4st3r1x** [comment]
Hi,

ok, so if i understand correctly. 
because all of the HTML was don't in Helvetica and i already made a body { font-family: Helvetica; }
i didn't need to add it to every ID i created?
