### ISSUE TITLE
IMPORTANT - img alt attribute

### ISSUE THREAD

**Issue by franfranfranfran** [4st3r1x/prj-rev-bwfs-dasmoto#4]
https://github.com/4st3r1x/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L15
https://github.com/4st3r1x/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/index.html#L24
etc...

make sure to use an alt attribute for each img element to ensure that a wider variety of users have access to the information contained in those images. more info can be found here - https://www.w3schools.com/tags/att_img_alt.asp

**Comment by 4st3r1x** [comment]
it wasn't in my course, now i know, thx
